/-
Copyright (c) 2026 James. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: James
-/
import Mathlib.Data.Real.Basic
import Mathlib.Tactic
import Mathlib.Topology.Basic

/-!
# Proof-complexity core interfaces

This module contains the lightweight syntactic and complexity interfaces shared
by the Sondow route and the local Hilbert proof-calculus model.
-/

-- Inductive type representing the formal proof systems
inductive ProofSystem
  | S21 -- Buss bounded arithmetic S_2^1, used as the verification base
  | PA  -- Peano Arithmetic (first-order)
  | Z2  -- Second-Order Arithmetic (with analysis)

-- Proof length must also specify what is being counted.  The line-count and
-- symbol/bit-size conventions can behave very differently in first-order logic.
inductive ProofLengthMeasure
  | symbolSize
  | lineCount
  | bitSize

-- A proof-complexity statement must refer to formula codes, not bare `Prop`.
-- This keeps the current model intensional enough to later attach an actual
-- proof calculus, Gödel coding, and length measure.
inductive FormulaFamily
  | sondowIdentity
  | sondowExplicitIdentity
  | sondowCertificateValid
  | sondowTailBoundCertificate
  | sondowDenominatorCertificate
  | sondowProductLogCertificate
  | partialConsistency
  | strengthenedPartialConsistency
  | sondowReflectionGraft

structure FormulaCode where
  family : FormulaFamily
  index : ℕ

def sondowIdentityCode (n : ℕ) : FormulaCode :=
  { family := FormulaFamily.sondowIdentity, index := n }

def sondowExplicitIdentityCode (n : ℕ) : FormulaCode :=
  { family := FormulaFamily.sondowExplicitIdentity, index := n }

def sondowCertificateValidCode (n : ℕ) : FormulaCode :=
  { family := FormulaFamily.sondowCertificateValid, index := n }

def sondowTailBoundCertificateCode (n : ℕ) : FormulaCode :=
  { family := FormulaFamily.sondowTailBoundCertificate, index := n }

def sondowDenominatorCertificateCode (n : ℕ) : FormulaCode :=
  { family := FormulaFamily.sondowDenominatorCertificate, index := n }

def sondowProductLogCertificateCode (n : ℕ) : FormulaCode :=
  { family := FormulaFamily.sondowProductLogCertificate, index := n }

def partialConsistencyCode (n : ℕ) : FormulaCode :=
  { family := FormulaFamily.partialConsistency, index := n }

def strengthenedPartialConsistencyCode (n : ℕ) : FormulaCode :=
  { family := FormulaFamily.strengthenedPartialConsistency, index := n }

def sondowReflectionGraftCode (n : ℕ) : FormulaCode :=
  { family := FormulaFamily.sondowReflectionGraft, index := n }

-- A concrete proof-code semantics for a chosen formula-code fragment.  It
-- separates the proof code carrier, the checker relation, and the size measure.
universe q

structure ProofCodeSemantics (relevant : FormulaCode → Prop) where
  Code : Type q
  checks : Code → FormulaCode → Prop
  size : Code → ℕ
  complete :
    ∀ code : FormulaCode, relevant code → ∃ c : Code, checks c code

def ProofCodeSemantics.HasProofCodeOfSize
    {relevant : FormulaCode → Prop} (sem : ProofCodeSemantics relevant)
    (code : FormulaCode) (k : ℕ) : Prop :=
  ∃ c : sem.Code, sem.checks c code ∧ sem.size c ≤ k

theorem ProofCodeSemantics.exists_hasProofCodeOfSize
    {relevant : FormulaCode → Prop} (sem : ProofCodeSemantics relevant)
    {code : FormulaCode} (hcode : relevant code) :
    ∃ k : ℕ, sem.HasProofCodeOfSize code k := by
  rcases sem.complete code hcode with ⟨c, hc⟩
  exact ⟨sem.size c, c, hc, le_rfl⟩

noncomputable def ProofCodeSemantics.minProofCodeSize
    {relevant : FormulaCode → Prop} (sem : ProofCodeSemantics relevant)
    (code : FormulaCode) (hcode : relevant code) : ℕ :=
  by
    classical
    exact Nat.find (sem.exists_hasProofCodeOfSize hcode)

theorem ProofCodeSemantics.hasProofCodeOfSize_minProofCodeSize
    {relevant : FormulaCode → Prop} (sem : ProofCodeSemantics relevant)
    {code : FormulaCode} (hcode : relevant code) :
    sem.HasProofCodeOfSize code (sem.minProofCodeSize code hcode) := by
  classical
  exact Nat.find_spec (sem.exists_hasProofCodeOfSize hcode)

theorem ProofCodeSemantics.minProofCodeSize_le_of_hasProofCodeOfSize
    {relevant : FormulaCode → Prop} (sem : ProofCodeSemantics relevant)
    {code : FormulaCode} (hcode : relevant code) {k : ℕ}
    (hk : sem.HasProofCodeOfSize code k) :
    sem.minProofCodeSize code hcode ≤ k := by
  classical
  exact Nat.find_min' (sem.exists_hasProofCodeOfSize hcode) hk

-- A total Nat-valued length function generated by a concrete proof-code
-- semantics on its intended fragment.  Outside the fragment it uses a fallback
-- length, so replacing the project-level `proof_length` can be staged without
-- assigning meanings to unrelated formula families.
noncomputable def ProofCodeSemantics.semanticProofLength
    {relevant : FormulaCode → Prop} (sem : ProofCodeSemantics relevant)
    (fallback : FormulaCode → ℕ) (code : FormulaCode) : ℕ := by
  classical
  exact if hcode : relevant code then sem.minProofCodeSize code hcode
    else fallback code

theorem ProofCodeSemantics.semanticProofLength_eq_minProofCodeSize
    {relevant : FormulaCode → Prop} (sem : ProofCodeSemantics relevant)
    (fallback : FormulaCode → ℕ) {code : FormulaCode} (hcode : relevant code) :
    sem.semanticProofLength fallback code =
      sem.minProofCodeSize code hcode := by
  classical
  simp [ProofCodeSemantics.semanticProofLength, hcode]

theorem ProofCodeSemantics.semanticProofLength_eq_fallback
    {relevant : FormulaCode → Prop} (sem : ProofCodeSemantics relevant)
    (fallback : FormulaCode → ℕ) {code : FormulaCode} (hcode : ¬ relevant code) :
    sem.semanticProofLength fallback code = fallback code := by
  classical
  simp [ProofCodeSemantics.semanticProofLength, hcode]

-- Real-valued project length induced by a concrete proof checker.  This is the
-- Cook-Reckhow style route: once proof codes, a checker relation, and a size
-- measure are fixed, the proof length of a formula is the minimum accepted
-- proof-code size on the intended fragment, with a staged fallback elsewhere.
noncomputable def ProofCodeSemantics.projectLength
    {relevant : FormulaCode → Prop} (sem : ProofCodeSemantics relevant)
    (fallback : FormulaCode → ℕ) (code : FormulaCode) : ℝ :=
  sem.semanticProofLength fallback code

theorem ProofCodeSemantics.projectLength_eq_minProofCodeSize
    {relevant : FormulaCode → Prop} (sem : ProofCodeSemantics relevant)
    (fallback : FormulaCode → ℕ) {code : FormulaCode} (hcode : relevant code) :
    sem.projectLength fallback code =
      sem.minProofCodeSize code hcode := by
  rw [ProofCodeSemantics.projectLength,
    sem.semanticProofLength_eq_minProofCodeSize fallback hcode]

theorem ProofCodeSemantics.projectLength_eq_fallback
    {relevant : FormulaCode → Prop} (sem : ProofCodeSemantics relevant)
    (fallback : FormulaCode → ℕ) {code : FormulaCode} (hcode : ¬ relevant code) :
    sem.projectLength fallback code = fallback code := by
  rw [ProofCodeSemantics.projectLength,
    sem.semanticProofLength_eq_fallback fallback hcode]

def ProofSystem.rootWeight : ProofSystem → Nat
  | ProofSystem.S21 => 1
  | ProofSystem.PA => 2
  | ProofSystem.Z2 => 3

def ProofLengthMeasure.rootWeight : ProofLengthMeasure → Nat
  | ProofLengthMeasure.symbolSize => 1
  | ProofLengthMeasure.lineCount => 2
  | ProofLengthMeasure.bitSize => 3

def FormulaFamily.rootWeight : FormulaFamily → Nat
  | FormulaFamily.sondowIdentity => 1
  | FormulaFamily.sondowExplicitIdentity => 2
  | FormulaFamily.sondowCertificateValid => 3
  | FormulaFamily.sondowTailBoundCertificate => 4
  | FormulaFamily.sondowDenominatorCertificate => 5
  | FormulaFamily.sondowProductLogCertificate => 6
  | FormulaFamily.partialConsistency => 7
  | FormulaFamily.strengthenedPartialConsistency => 8
  | FormulaFamily.sondowReflectionGraft => 9

def rootFormulaCodeSize
    (T : ProofSystem) (measure : ProofLengthMeasure)
    (code : FormulaCode) : Nat :=
  match T, measure, code.family with
  | ProofSystem.S21, ProofLengthMeasure.symbolSize,
      FormulaFamily.sondowCertificateValid => 1
  | _, _, _ =>
      code.index + code.family.rootWeight + T.rootWeight + measure.rootWeight + 1

def rootRelevantFormulaCode (_code : FormulaCode) : Prop :=
  True

/--
Root proof-code semantics for the project-level `proof_length`.

This removes the former free proof-length axiom.  On
`S21 / symbolSize / sondowCertificateValidCode` it reserves the canonical
Sondow sidecar slot of length `1`; on all other families it uses the structural
fallback code-size convention above.  The sidecar slot is calibrated in the
Sondow integration layer, where the corresponding proof-code checker is
available without creating an import cycle.

Submission-level theorems should not cite this as the PA/Hilbert proof-length
model outside the calibrated family.  A literature-calibrated route for other
families must instead fix a concrete `FormulaCode -> PA formula`
interpretation and use the corresponding MiniHilbert / checked-code semantics.
-/
def rootProofCodeSemantics
    (T : ProofSystem) (measure : ProofLengthMeasure) :
    ProofCodeSemantics.{0} rootRelevantFormulaCode where
  Code := FormulaCode
  checks := fun c code => c = code
  size := rootFormulaCodeSize T measure
  complete := by
    intro code _hcode
    exact ⟨code, rfl⟩

noncomputable def rootSemanticProofLength
    (T : ProofSystem) (measure : ProofLengthMeasure)
    (code : FormulaCode) : Nat :=
  (rootProofCodeSemantics T measure).minProofCodeSize code trivial

theorem rootSemanticProofLength_eq_rootFormulaCodeSize
    (T : ProofSystem) (measure : ProofLengthMeasure)
    (code : FormulaCode) :
    rootSemanticProofLength T measure code =
      rootFormulaCodeSize T measure code := by
  let sem := rootProofCodeSemantics T measure
  apply Nat.le_antisymm
  · exact sem.minProofCodeSize_le_of_hasProofCodeOfSize trivial
      ⟨code, rfl, le_rfl⟩
  · rcases sem.hasProofCodeOfSize_minProofCodeSize
        (code := code) trivial with ⟨c, hchecks, hsize⟩
    subst hchecks
    exact hsize

/--
Project-level root proof length.

This is a definition induced by `rootProofCodeSemantics`, not an axiom.
-/
noncomputable def proof_length
    (T : ProofSystem) (measure : ProofLengthMeasure)
    (code : FormulaCode) : ℝ :=
  rootSemanticProofLength T measure code

theorem proof_length_eq_rootFormulaCodeSize
    (T : ProofSystem) (measure : ProofLengthMeasure)
    (code : FormulaCode) :
    proof_length T measure code =
      (rootFormulaCodeSize T measure code : ℝ) := by
  rw [proof_length, rootSemanticProofLength_eq_rootFormulaCodeSize]

/-- Root length of the Sondow certificate-valid family after sidecar-slot calibration. -/
theorem rootProofLength_sondowCertificateValidCode_eq_one
    (n : Nat) :
    proof_length ProofSystem.S21 ProofLengthMeasure.symbolSize
        (sondowCertificateValidCode n) = (1 : Real) := by
  rw [proof_length_eq_rootFormulaCodeSize]
  simp [rootFormulaCodeSize, sondowCertificateValidCode]

/--
Structural fallback value that would have been assigned without the calibrated
Sondow sidecar slot.
-/
theorem structuralFallbackFormulaSize_sondowCertificateValidCode_eq_add_six
    (n : Nat) :
    (sondowCertificateValidCode n).index +
        (sondowCertificateValidCode n).family.rootWeight +
        ProofSystem.S21.rootWeight +
        ProofLengthMeasure.symbolSize.rootWeight + 1 =
      n + 6 := by
  simp [sondowCertificateValidCode, FormulaFamily.rootWeight,
    ProofSystem.rootWeight, ProofLengthMeasure.rootWeight]

-- A semantic source for the abstract `proof_length`: a concrete Nat-valued
-- code-length model whose values agree with the project-level real-valued
-- `proof_length` on a specified family of formula codes.
structure ProjectProofLengthSemantics
    (T : ProofSystem) (measure : ProofLengthMeasure)
    (length : FormulaCode → ℕ) (relevant : FormulaCode → Prop) : Prop where
  proof_length_eq :
    ∀ code : FormulaCode, relevant code →
      proof_length T measure code = length code

structure ProofLengthCodeSemantics
    (T : ProofSystem) (measure : ProofLengthMeasure)
    (relevant : FormulaCode → Prop) where
  proof_code_semantics : ProofCodeSemantics.{q} relevant
  fallback_length : FormulaCode → ℕ

noncomputable def ProofLengthCodeSemantics.length
    {T : ProofSystem} {measure : ProofLengthMeasure}
    {relevant : FormulaCode → Prop}
    (model : ProofLengthCodeSemantics T measure relevant) :
    FormulaCode → ℕ :=
  model.proof_code_semantics.semanticProofLength model.fallback_length

structure ProofLengthCodeSemantics.Calibration
    {T : ProofSystem} {measure : ProofLengthMeasure}
    {relevant : FormulaCode → Prop}
    (model : ProofLengthCodeSemantics T measure relevant) : Prop where
  proof_length_eq_length :
    ∀ code : FormulaCode, relevant code →
      proof_length T measure code = model.length code

theorem ProofLengthCodeSemantics.Calibration.toProjectProofLengthSemantics
    {T : ProofSystem} {measure : ProofLengthMeasure}
    {relevant : FormulaCode → Prop}
    {model : ProofLengthCodeSemantics T measure relevant}
    (hcal : model.Calibration) :
    ProjectProofLengthSemantics T measure model.length relevant where
  proof_length_eq := hcal.proof_length_eq_length

theorem ProofLengthCodeSemantics.Calibration.proof_length_eq_minProofCodeSize
    {T : ProofSystem} {measure : ProofLengthMeasure}
    {relevant : FormulaCode → Prop}
    {model : ProofLengthCodeSemantics T measure relevant}
    (hcal : model.Calibration)
    {code : FormulaCode} (hcode : relevant code) :
    proof_length T measure code =
      model.proof_code_semantics.minProofCodeSize code hcode := by
  rw [hcal.proof_length_eq_length code hcode]
  rw [ProofLengthCodeSemantics.length]
  rw [ProofCodeSemantics.semanticProofLength_eq_minProofCodeSize]

theorem ProofLengthCodeSemantics.Calibration.proof_length_le_of_hasProofCodeOfSize
    {T : ProofSystem} {measure : ProofLengthMeasure}
    {relevant : FormulaCode → Prop}
    {model : ProofLengthCodeSemantics T measure relevant}
    (hcal : model.Calibration)
    {code : FormulaCode} (hcode : relevant code) {k : Nat}
    (hk : model.proof_code_semantics.HasProofCodeOfSize code k) :
    proof_length T measure code ≤ (k : Real) := by
  rw [hcal.proof_length_eq_minProofCodeSize hcode]
  exact_mod_cast
    model.proof_code_semantics.minProofCodeSize_le_of_hasProofCodeOfSize
      hcode hk

structure RootProofLengthCodeConvention
    (T : ProofSystem) (measure : ProofLengthMeasure)
    (relevant : FormulaCode → Prop) where
  model : ProofLengthCodeSemantics T measure relevant
  calibration : model.Calibration

namespace RootProofLengthCodeConvention

def ofCalibration
    {T : ProofSystem} {measure : ProofLengthMeasure}
    {relevant : FormulaCode → Prop}
    (model : ProofLengthCodeSemantics T measure relevant)
    (calibration : model.Calibration) :
    RootProofLengthCodeConvention T measure relevant where
  model := model
  calibration := calibration

noncomputable def length
    {T : ProofSystem} {measure : ProofLengthMeasure}
    {relevant : FormulaCode → Prop}
    (conv : RootProofLengthCodeConvention T measure relevant) :
    FormulaCode → Nat :=
  conv.model.length

theorem proof_length_eq_minProofCodeSize
    {T : ProofSystem} {measure : ProofLengthMeasure}
    {relevant : FormulaCode → Prop}
    (conv : RootProofLengthCodeConvention T measure relevant)
    {code : FormulaCode} (hcode : relevant code) :
    proof_length T measure code =
      conv.model.proof_code_semantics.minProofCodeSize code hcode :=
  conv.calibration.proof_length_eq_minProofCodeSize hcode

theorem proof_length_le_of_hasProofCodeOfSize
    {T : ProofSystem} {measure : ProofLengthMeasure}
    {relevant : FormulaCode → Prop}
    (conv : RootProofLengthCodeConvention T measure relevant)
    {code : FormulaCode} (hcode : relevant code) {k : Nat}
    (hk : conv.model.proof_code_semantics.HasProofCodeOfSize code k) :
    proof_length T measure code ≤ (k : Real) :=
  conv.calibration.proof_length_le_of_hasProofCodeOfSize hcode hk

theorem toProjectProofLengthSemantics
    {T : ProofSystem} {measure : ProofLengthMeasure}
    {relevant : FormulaCode → Prop}
    (conv : RootProofLengthCodeConvention T measure relevant) :
    ProjectProofLengthSemantics T measure conv.length relevant :=
  conv.calibration.toProjectProofLengthSemantics

end RootProofLengthCodeConvention

noncomputable def rootProofLengthCodeSemantics
    (T : ProofSystem) (measure : ProofLengthMeasure) :
    ProofLengthCodeSemantics T measure rootRelevantFormulaCode where
  proof_code_semantics := rootProofCodeSemantics T measure
  fallback_length := fun _ => 0

theorem rootProofLengthCodeSemantics_calibration
    (T : ProofSystem) (measure : ProofLengthMeasure) :
    (rootProofLengthCodeSemantics T measure).Calibration where
  proof_length_eq_length := by
    intro code _hcode
    simp [rootProofLengthCodeSemantics, ProofLengthCodeSemantics.length,
      ProofCodeSemantics.semanticProofLength, rootRelevantFormulaCode,
      proof_length, rootSemanticProofLength]

noncomputable def rootStructuralProofLengthCodeConvention
    (T : ProofSystem) (measure : ProofLengthMeasure) :
    RootProofLengthCodeConvention T measure rootRelevantFormulaCode :=
  RootProofLengthCodeConvention.ofCalibration
    (rootProofLengthCodeSemantics T measure)
    (rootProofLengthCodeSemantics_calibration T measure)

theorem rootStructuralProofLength_eq_minProofCodeSize
    (T : ProofSystem) (measure : ProofLengthMeasure)
    (code : FormulaCode) :
    proof_length T measure code =
      (rootProofCodeSemantics T measure).minProofCodeSize code trivial := by
  exact
    RootProofLengthCodeConvention.proof_length_eq_minProofCodeSize
      (rootStructuralProofLengthCodeConvention T measure) trivial

def ProofCodeSemantics.toProjectProofLengthSemantics
    {relevant : FormulaCode → Prop} (sem : ProofCodeSemantics relevant)
    (T : ProofSystem) (measure : ProofLengthMeasure) (length : FormulaCode → ℕ)
    (hlength :
      ∀ code : FormulaCode, ∀ hcode : relevant code,
        length code = sem.minProofCodeSize code hcode)
    (hproof_length :
      ∀ code : FormulaCode, ∀ hcode : relevant code,
        proof_length T measure code = sem.minProofCodeSize code hcode) :
    ProjectProofLengthSemantics T measure length relevant where
  proof_length_eq := by
    intro code hcode
    rw [hproof_length code hcode]
    rw [hlength code hcode]

-- Compatibility convention for older statements.  The proof-complexity audit
-- recommends symbol/bit-size over bare line count; existing conditional
-- theorems are kept on symbol size until a real calculus is selected.
def defaultProofLengthMeasure : ProofLengthMeasure :=
  ProofLengthMeasure.symbolSize

noncomputable def default_proof_length (T : ProofSystem) (φ : FormulaCode) : ℝ :=
  proof_length T defaultProofLengthMeasure φ

-- Definition of polynomial bound for complexity growth
def is_polynomial_bound (f : ℕ → ℝ) : Prop :=
  ∃ (c : ℝ) (k : ℕ), ∀ n : ℕ, f n ≤ c * ((n : ℝ) + 1)^k

theorem is_polynomial_bound.linear_rescale
    {f : ℕ → ℝ} (hf : is_polynomial_bound f)
    {C D : ℝ} (hC : 0 ≤ C) (hD : 0 ≤ D) :
    is_polynomial_bound (fun n : ℕ => C * f n + D) := by
  rcases hf with ⟨c, k, hc⟩
  refine ⟨C * c + D, k, ?_⟩
  intro n
  have hbase : (1 : ℝ) ≤ (n : ℝ) + 1 := by
    nlinarith [show (0 : ℝ) ≤ (n : ℝ) by exact Nat.cast_nonneg n]
  have hpow : (1 : ℝ) ≤ ((n : ℝ) + 1)^k :=
    one_le_pow₀ hbase
  have hmul : C * f n ≤ C * (c * ((n : ℝ) + 1)^k) :=
    mul_le_mul_of_nonneg_left (hc n) hC
  have hDpow : D ≤ D * ((n : ℝ) + 1)^k := by
    nlinarith [mul_le_mul_of_nonneg_left hpow hD]
  nlinarith

theorem is_polynomial_bound_of_le
    {f g : ℕ → ℝ} (hfg : ∀ n : ℕ, f n ≤ g n)
    (hg : is_polynomial_bound g) :
    is_polynomial_bound f := by
  rcases hg with ⟨c, k, hc⟩
  exact ⟨c, k, fun n => le_trans (hfg n) (hc n)⟩

theorem is_polynomial_bound.nonneg_coefficient
    {f : ℕ → ℝ} (hf : is_polynomial_bound f) :
    ∃ (c : ℝ) (k : ℕ), 0 ≤ c ∧
      ∀ n : ℕ, f n ≤ c * ((n : ℝ) + 1)^k := by
  rcases hf with ⟨c, k, hc⟩
  refine ⟨|c|, k, abs_nonneg c, ?_⟩
  intro n
  have hbase_nonneg : 0 ≤ (n : ℝ) + 1 := by
    positivity
  have hpow_nonneg : 0 ≤ ((n : ℝ) + 1)^k :=
    pow_nonneg hbase_nonneg k
  exact (hc n).trans (mul_le_mul_of_nonneg_right (le_abs_self c) hpow_nonneg)

theorem is_polynomial_bound.comp_nat
    {f : ℕ → ℝ} {ρ : ℕ → ℕ}
    (hf : is_polynomial_bound f)
    (hρ : is_polynomial_bound (fun n : ℕ => (ρ n : ℝ))) :
    is_polynomial_bound (fun n : ℕ => f (ρ n)) := by
  rcases hf.nonneg_coefficient with ⟨cf, kf, hcf_nonneg, hcf⟩
  rcases hρ.nonneg_coefficient with ⟨cρ, kρ, hcρ_nonneg, hcρ⟩
  refine ⟨cf * (cρ + 1)^kf, kρ * kf, ?_⟩
  intro n
  have hnbase : 1 ≤ (n : ℝ) + 1 := by
    nlinarith [show (0 : ℝ) ≤ (n : ℝ) by exact Nat.cast_nonneg n]
  have hnbase_nonneg : 0 ≤ (n : ℝ) + 1 := by positivity
  have hnbase_pow_nonneg : 0 ≤ ((n : ℝ) + 1)^kρ :=
    pow_nonneg hnbase_nonneg kρ
  have hone_le_pow : 1 ≤ ((n : ℝ) + 1)^kρ :=
    one_le_pow₀ hnbase
  have hρ_bound := hcρ n
  have hρ_nonneg : 0 ≤ (ρ n : ℝ) := by exact Nat.cast_nonneg (ρ n)
  have hρ_add_bound :
      (ρ n : ℝ) + 1 ≤ (cρ + 1) * ((n : ℝ) + 1)^kρ := by
    have h1 :
        (1 : ℝ) ≤ 1 * ((n : ℝ) + 1)^kρ := by
      simpa using hone_le_pow
    calc
      (ρ n : ℝ) + 1 ≤ cρ * ((n : ℝ) + 1)^kρ +
          1 * ((n : ℝ) + 1)^kρ := by
        exact add_le_add hρ_bound h1
      _ = (cρ + 1) * ((n : ℝ) + 1)^kρ := by ring
  have hcρ_add_nonneg : 0 ≤ cρ + 1 := by nlinarith
  have hρ_add_nonneg : 0 ≤ (ρ n : ℝ) + 1 := by positivity
  have hpow_arg :
      ((ρ n : ℝ) + 1)^kf ≤
        ((cρ + 1) * ((n : ℝ) + 1)^kρ)^kf :=
    pow_le_pow_left₀ hρ_add_nonneg hρ_add_bound kf
  have htarget_nonneg :
      0 ≤ ((cρ + 1) * ((n : ℝ) + 1)^kρ)^kf :=
    pow_nonneg (mul_nonneg hcρ_add_nonneg hnbase_pow_nonneg) kf
  have hmul_pow :
      ((cρ + 1) * ((n : ℝ) + 1)^kρ)^kf =
        (cρ + 1)^kf * ((n : ℝ) + 1)^(kρ * kf) := by
    rw [mul_pow, ← pow_mul]
  calc
    f (ρ n) ≤ cf * (((ρ n : ℝ) + 1)^kf) := hcf (ρ n)
    _ ≤ cf * (((cρ + 1) * ((n : ℝ) + 1)^kρ)^kf) := by
      exact mul_le_mul_of_nonneg_left hpow_arg hcf_nonneg
    _ = cf * ((cρ + 1)^kf * ((n : ℝ) + 1)^(kρ * kf)) := by
      rw [hmul_pow]
    _ = cf * (cρ + 1)^kf * ((n : ℝ) + 1)^(kρ * kf) := by ring

open Filter

structure EventualLowerBound
    (T : ProofSystem) (measure : ProofLengthMeasure) (φ : ℕ → FormulaCode) :
    Prop where
  lower_bound :
    ∀ f : ℕ → ℝ, is_polynomial_bound f →
      ∀ N : ℕ, ∃ n : ℕ, N ≤ n ∧ proof_length T measure (φ n) > f n

theorem EventualLowerBound.of_frequently
    {T : ProofSystem} {measure : ProofLengthMeasure} {φ : ℕ → FormulaCode}
    (hfreq :
      ∀ f : ℕ → ℝ, is_polynomial_bound f →
        ∃ᶠ n in atTop, proof_length T measure (φ n) > f n) :
    EventualLowerBound T measure φ where
  lower_bound := by
    intro f hf N
    exact (Filter.frequently_atTop.mp (hfreq f hf)) N

/-- A standalone eventual strict gap certificate between an upper function `U`
and a lower/measured function `L`.  This is intentionally independent from the
Pudlak lower-bound package: auditors can check that the final contradiction
uses a separately exposed `U n < L n` witness, not an implicit reading of
`EventualLowerBound`. -/
structure EventualStrictGap (U L : ℕ → ℝ) : Prop where
  gap_after : ∀ N : ℕ, ∃ n : ℕ, N ≤ n ∧ U n < L n

/-- Read an `EventualLowerBound` as a gap certificate against one fixed
polynomial upper function.  In collision proofs this is the exact point where
the Pudlak-side irreducibility is converted into the explicit gap
`U n < proof_length ...`. -/
def EventualLowerBound.toProofLengthGap
    {T : ProofSystem} {measure : ProofLengthMeasure} {φ : ℕ → FormulaCode}
    (hlower : EventualLowerBound T measure φ)
    (U : ℕ → ℝ) (hU : is_polynomial_bound U) :
    EventualStrictGap U (fun n => proof_length T measure (φ n)) where
  gap_after := by
    intro N
    rcases hlower.lower_bound U hU N with ⟨n, hn_ge, hgap⟩
    exact ⟨n, hn_ge, hgap⟩

/-- Pure arithmetic collision core: a proof-length upper bound and an explicit
strict gap cannot hold on the same tail. -/
theorem collisionCore_from_lower_upper_gap
    {T : ProofSystem} {measure : ProofLengthMeasure} {φ : ℕ → FormulaCode}
    {U : ℕ → ℝ}
    (hgap :
      EventualStrictGap U (fun n => proof_length T measure (φ n)))
    (N : ℕ)
    (hupper :
      ∀ n : ℕ, N ≤ n → proof_length T measure (φ n) ≤ U n) :
    False := by
  rcases hgap.gap_after N with ⟨n, hn_ge, hlt⟩
  exact (not_lt_of_ge (hupper n hn_ge)) hlt

structure StrongProofLengthLowerBound
    (T : ProofSystem) (measure : ProofLengthMeasure) (φ : ℕ → FormulaCode) :
    Prop where
  frequently_beats_every_polynomial :
    ∀ f : ℕ → ℝ, is_polynomial_bound f →
      ∃ᶠ n in atTop, proof_length T measure (φ n) > f n

structure StrongLowerBoundTransfer
    (T : ProofSystem) (measure : ProofLengthMeasure)
    (source target : ℕ → FormulaCode) : Prop where
  transfer :
    ∀ f : ℕ → ℝ, is_polynomial_bound f →
      ∃ g : ℕ → ℝ, is_polynomial_bound g ∧
        ((∃ᶠ n in atTop, proof_length T measure (source n) > g n) →
            ∃ᶠ n in atTop, proof_length T measure (target n) > f n)

theorem StrongProofLengthLowerBound.transfer
    {T : ProofSystem} {measure : ProofLengthMeasure}
    {source target : ℕ → FormulaCode}
    (hsource : StrongProofLengthLowerBound T measure source)
    (htransfer : StrongLowerBoundTransfer T measure source target) :
    StrongProofLengthLowerBound T measure target where
  frequently_beats_every_polynomial := by
    intro f hf
    rcases htransfer.transfer f hf with ⟨g, hg_poly, htransfer_g⟩
    exact htransfer_g (hsource.frequently_beats_every_polynomial g hg_poly)

theorem StrongProofLengthLowerBound.congr
    {T : ProofSystem} {measure : ProofLengthMeasure}
    {source target : ℕ → FormulaCode}
    (hsource : StrongProofLengthLowerBound T measure source)
    (hcode : ∀ n : ℕ, source n = target n) :
    StrongProofLengthLowerBound T measure target where
  frequently_beats_every_polynomial := by
    intro f hf
    exact (hsource.frequently_beats_every_polynomial f hf).mono
      (fun n hn => by simpa [hcode n] using hn)

theorem StrongProofLengthLowerBound.congr_symm
    {T : ProofSystem} {measure : ProofLengthMeasure}
    {source target : ℕ → FormulaCode}
    (htarget : StrongProofLengthLowerBound T measure target)
    (hcode : ∀ n : ℕ, source n = target n) :
    StrongProofLengthLowerBound T measure source where
  frequently_beats_every_polynomial := by
    intro f hf
    exact (htarget.frequently_beats_every_polynomial f hf).mono
      (fun n hn => by simpa [hcode n] using hn)

theorem StrongLowerBoundTransfer.comp
    {T : ProofSystem} {measure : ProofLengthMeasure}
    {source middle target : ℕ → FormulaCode}
    (h₁ : StrongLowerBoundTransfer T measure source middle)
    (h₂ : StrongLowerBoundTransfer T measure middle target) :
    StrongLowerBoundTransfer T measure source target where
  transfer := by
    intro f hf
    rcases h₂.transfer f hf with ⟨g, hg_poly, hg_to_target⟩
    rcases h₁.transfer g hg_poly with ⟨k, hk_poly, hk_to_middle⟩
    exact ⟨k, hk_poly, fun hsource => hg_to_target (hk_to_middle hsource)⟩

theorem StrongProofLengthLowerBound.toEventualLowerBound
    {T : ProofSystem} {measure : ProofLengthMeasure} {φ : ℕ → FormulaCode}
    (h : StrongProofLengthLowerBound T measure φ) :
    EventualLowerBound T measure φ :=
  EventualLowerBound.of_frequently h.frequently_beats_every_polynomial

structure PolynomialCofinalScale (ρ : ℕ → ℕ) : Prop where
  cofinal : ∀ M : ℕ, ∃ N : ℕ, ∀ n : ℕ, N ≤ n → M ≤ ρ n
  polynomial_substitution :
    ∀ f : ℕ → ℝ, is_polynomial_bound f →
      is_polynomial_bound (fun n : ℕ => f (ρ n))

theorem PolynomialCofinalScale.id :
    PolynomialCofinalScale (fun n : ℕ => n) where
  cofinal := by
    intro M
    exact ⟨M, fun n hn => hn⟩
  polynomial_substitution := by
    intro f hf
    simpa using hf

theorem PolynomialCofinalScale.of_id_le_and_polynomial_bound
    {ρ : ℕ → ℕ}
    (hid : ∀ n : ℕ, n ≤ ρ n)
    (hpoly : is_polynomial_bound (fun n : ℕ => (ρ n : ℝ))) :
    PolynomialCofinalScale ρ where
  cofinal := by
    intro M
    exact ⟨M, fun n hn => le_trans hn (hid n)⟩
  polynomial_substitution := by
    intro f hf
    exact hf.comp_nat hpoly

theorem PolynomialCofinalScale.comp
    {ρ σ : ℕ → ℕ}
    (hρ : PolynomialCofinalScale ρ)
    (hσ : PolynomialCofinalScale σ) :
    PolynomialCofinalScale (fun n : ℕ => ρ (σ n)) where
  cofinal := by
    intro M
    rcases hρ.cofinal M with ⟨Nρ, hNρ⟩
    rcases hσ.cofinal Nρ with ⟨Nσ, hNσ⟩
    exact ⟨Nσ, fun n hn => hNρ (σ n) (hNσ n hn)⟩
  polynomial_substitution := by
    intro f hf
    exact hσ.polynomial_substitution
      (fun m : ℕ => f (ρ m)) (hρ.polynomial_substitution f hf)

theorem frequently_atTop_of_frequently_scale
    {ρ : ℕ → ℕ} (hscale : PolynomialCofinalScale ρ) {P : ℕ → Prop}
    (hfreq : ∃ᶠ n in atTop, P (ρ n)) :
    ∃ᶠ m in atTop, P m := by
  rw [Filter.frequently_atTop] at hfreq ⊢
  intro M
  rcases hscale.cofinal M with ⟨N, hN⟩
  rcases hfreq N with ⟨n, hn_ge, hnP⟩
  exact ⟨ρ n, hN n hn_ge, hnP⟩

theorem StrongLowerBoundTransfer.of_polynomial_cofinal_scale
    {T : ProofSystem} {measure : ProofLengthMeasure}
    {φ : ℕ → FormulaCode} {ρ : ℕ → ℕ}
    (hscale : PolynomialCofinalScale ρ) :
    StrongLowerBoundTransfer T measure (fun n : ℕ => φ (ρ n)) φ where
  transfer := by
    intro f hf
    refine ⟨fun n : ℕ => f (ρ n), hscale.polynomial_substitution f hf, ?_⟩
    intro hfreq
    exact frequently_atTop_of_frequently_scale hscale hfreq

structure ProofLengthProjection
    (T : ProofSystem) (measure : ProofLengthMeasure)
    (source target : ℕ → FormulaCode) : Prop where
  source_le_target :
    ∀ n : ℕ, proof_length T measure (source n) ≤ proof_length T measure (target n)

-- A more realistic projection shape for proof-calculus transformations:
-- extracting the right conjunct from a proof of `A ∧ B` usually adds a fixed
-- rule/axiom tail, so it gives a linear bound rather than the zero-overhead
-- monotonicity encoded by `ProofLengthProjection`.
structure LinearProofLengthProjection
    (T : ProofSystem) (measure : ProofLengthMeasure)
    (source target : ℕ → FormulaCode) where
  C : ℝ
  D : ℝ
  C_pos : 0 < C
  D_nonneg : 0 ≤ D
  source_le_linear_target :
    ∀ n : ℕ,
      proof_length T measure (source n) ≤
        C * proof_length T measure (target n) + D

structure ConstantProofLengthProjection
    (T : ProofSystem) (measure : ProofLengthMeasure)
    (source target : ℕ → FormulaCode) where
  D : ℝ
  D_nonneg : 0 ≤ D
  source_le_target_add :
    ∀ n : ℕ,
      proof_length T measure (source n) ≤
        proof_length T measure (target n) + D

theorem ProofLengthProjection.refl
    (T : ProofSystem) (measure : ProofLengthMeasure)
    (φ : ℕ → FormulaCode) :
    ProofLengthProjection T measure φ φ where
  source_le_target := by
    intro n
    rfl

def ConstantProofLengthProjection.refl
    (T : ProofSystem) (measure : ProofLengthMeasure)
    (φ : ℕ → FormulaCode) :
    ConstantProofLengthProjection T measure φ φ where
  D := 0
  D_nonneg := by norm_num
  source_le_target_add := by
    intro n
    simp

def LinearProofLengthProjection.refl
    (T : ProofSystem) (measure : ProofLengthMeasure)
    (φ : ℕ → FormulaCode) :
    LinearProofLengthProjection T measure φ φ where
  C := 1
  D := 0
  C_pos := by norm_num
  D_nonneg := by norm_num
  source_le_linear_target := by
    intro n
    simp

def ConstantProofLengthProjection.toLinearProofLengthProjection
    {T : ProofSystem} {measure : ProofLengthMeasure}
    {source target : ℕ → FormulaCode}
    (h : ConstantProofLengthProjection T measure source target) :
    LinearProofLengthProjection T measure source target where
  C := 1
  D := h.D
  C_pos := by norm_num
  D_nonneg := h.D_nonneg
  source_le_linear_target := by
    intro n
    simpa using h.source_le_target_add n

def ProofLengthProjection.toStrongLowerBoundTransfer
    {T : ProofSystem} {measure : ProofLengthMeasure}
    {source target : ℕ → FormulaCode}
    (h : ProofLengthProjection T measure source target) :
    StrongLowerBoundTransfer T measure source target where
  transfer := by
    intro f hf
    refine ⟨f, hf, ?_⟩
    intro hfreq
    exact hfreq.mono fun n hn => lt_of_lt_of_le hn (h.source_le_target n)

def LinearProofLengthProjection.toStrongLowerBoundTransfer
    {T : ProofSystem} {measure : ProofLengthMeasure}
    {source target : ℕ → FormulaCode}
    (h : LinearProofLengthProjection T measure source target) :
    StrongLowerBoundTransfer T measure source target where
  transfer := by
    intro f hf
    refine ⟨fun n => h.C * f n + h.D,
      hf.linear_rescale h.C_pos.le h.D_nonneg, ?_⟩
    intro hfreq
    exact hfreq.mono fun n hn => by
      have hle := h.source_le_linear_target n
      nlinarith [h.C_pos, hn, hle]

theorem EventualLowerBound.transfer_of_projection
    {T : ProofSystem} {measure : ProofLengthMeasure}
    {source target : ℕ → FormulaCode}
    (hsource : EventualLowerBound T measure source)
    (hprojection : ProofLengthProjection T measure source target) :
    EventualLowerBound T measure target where
  lower_bound := by
    intro f hf N
    rcases hsource.lower_bound f hf N with ⟨n, hn_ge, hn_gt⟩
    exact ⟨n, hn_ge, lt_of_lt_of_le hn_gt (hprojection.source_le_target n)⟩
