import integration.FoundationCompactNumericListedDirectParserSyntaxFormulaRelationValidCertificate
import integration.FoundationCompactNumericListedDirectParserSyntaxFormulaRelationInvalidCertificate

/-! Checked certificates for both long relation branches. -/
