import integration.FoundationCompactNumericListedDirectParserSyntaxStepDoneDirectSelectedBounds

open FoundationCompactNumericListedDirectParserDoneFormulaEnvironmentAlignment
open FoundationCompactNumericListedDirectParserDoneFormulaSyntaxFixedBounds
open FoundationCompactNumericListedDirectParserDoneWholeUniformDirectFixedBounds
open FoundationCompactNumericListedDirectParserSyntaxStepDoneDirectSelectedBounds

#print axioms compactUnifiedParserDoneClosedFormula_environment_alignment
#print axioms compactUnifiedParserDoneClosedFormula_code_length_le_fixed
#print axioms
  compileCompactUnifiedParserDoneUniformDirectOriginalContext_payloadLength_le_fixed
#print axioms
  compileCompactUnifiedParserSyntaxStepFromDoneDirectContext_payloadLength_le_selected
