import integration.FoundationCompactNumericListedDirectParserSyntaxStepAllBranchesClosedFixedBounds

open FoundationCompactNumericListedDirectParserSyntaxStepAllBranchesClosedFixedBase
open FoundationCompactNumericListedDirectParserSyntaxStepDoneClosedFixedBound
open FoundationCompactNumericListedDirectParserSyntaxStepEmptyClosedFixedBound
open FoundationCompactNumericListedDirectParserSyntaxStepRepeatClosedFixedBound
open FoundationCompactNumericListedDirectParserSyntaxStepTermClosedFixedBound
open FoundationCompactNumericListedDirectParserSyntaxStepFormulaClosedFixedBound
open FoundationCompactNumericListedDirectParserSyntaxStepInvalidClosedFixedBound
open FoundationCompactNumericListedDirectParserSyntaxStepAllBranchesClosedFixedBounds

#print axioms compactUnifiedParserSyntaxStepDoneClosedFixedBound
#print axioms compactUnifiedParserSyntaxStepEmptyClosedFixedBound
#print axioms compactUnifiedParserSyntaxStepRepeatClosedFixedBound
#print axioms compactUnifiedParserSyntaxStepTermClosedFixedBound
#print axioms compactUnifiedParserSyntaxStepFormulaClosedFixedBound
#print axioms compactUnifiedParserSyntaxStepInvalidClosedFixedBound
#print axioms compactUnifiedParserSyntaxStepFullyFixedBoundFromData
#print axioms compactUnifiedParserSyntaxStepFullyFixedBoundOfGraph
