import integration.FoundationCompactNumericListedDirectParserEmptyUniformDirectAlignment
import integration.FoundationCompactNumericListedDirectParserEmptyUniformDirectOriginalFixedBounds

open FoundationCompactPADirectNineConjunctionCompiler
open FoundationCompactNumericListedDirectParserEmptyUniformDirectCompiler
open FoundationCompactNumericListedDirectParserEmptyUniformDirectAlignment
open FoundationCompactNumericListedDirectParserEmptyUniformDirectFixedBounds
open FoundationCompactNumericListedDirectParserEmptyUniformDirectOriginalFixedBounds

#print axioms compileDirectNineConjunction
#print axioms compileDirectNineConjunction_payloadLength_le_transparent
#print axioms compileCompactUnifiedParserEmptyUniformDirectContext
#print axioms compileCompactUnifiedParserEmptyUniformDirectOriginalContext
#print axioms
  compileCompactUnifiedParserEmptyUniformDirectContext_payloadLength_le_fixed
#print axioms
  compileCompactUnifiedParserEmptyUniformDirectOriginalContext_payloadLength_le_fixed
