import integration.FoundationCompactNumericListedDirectFormulaTransformTermOutputRowsNativeLeFixedBounds

open FoundationCompactNumericListedDirectFormulaTransformTermOutputRowsAtomicFixedBounds

#print axioms termRowsNativeEqCertificate_structuralPayloadBound_le_fixed
#print axioms termRowsNativeNeCertificate_structuralPayloadBound_le_fixed
#print axioms termRowsNativeLtCertificate_structuralPayloadBound_le_fixed
#print axioms consumedCountEqualityCertificate_structuralPayloadBound_le_fixed
#print axioms termRowsNativeLeStructuralEnvelope_le_fixed_of_closed
#print axioms termRowsNativeLeCertificate_structuralPayloadBound_le_fixed
#print axioms consumedCountPositiveCertificate_structuralPayloadBound_le_fixed
