import integration.FoundationCompactNumericListedDirectFormulaTransformTermOutputRowsFailureTripleFixedBound

open FoundationCompactNumericListedDirectFormulaTransformTermOutputRowsFailureFixedBounds
open FoundationCompactNumericListedDirectFormulaTransformTermOutputRowsFailureTripleFixedBound

#check doubleFailurePublicFinitePayloadEnvelope_le_fullyFixed
#check tripleFailurePublicFinitePayloadEnvelope_le_fullyFixed

#print axioms doubleFailurePublicFinitePayloadEnvelope_le_fullyFixed
#print axioms tripleFailurePublicFinitePayloadEnvelope_le_fullyFixed
