import integration.FoundationCompactNumericListedDirectParserSyntaxFormulaCheckedDataFullyFixedBounds

open FoundationCompactNumericListedDirectParserSyntaxFormulaCheckedDataFullyFixedBounds

#check
  compactUnifiedParserSyntaxFormulaBranchCleanHybridCertificateFromData_structuralPayloadBound_le_fullyFixed

#print axioms
  compactUnifiedParserSyntaxFormulaBranchCleanHybridCertificateFromData_structuralPayloadBound_le_fullyFixed
