import integration.FoundationCompactNumericListedDirectParserDoneUniformDirectFixedBounds

open FoundationCompactNumericListedDirectParserDoneUniformDirectCompiler
open FoundationCompactNumericListedDirectParserDoneUniformDirectFixedBounds

#print axioms compileCompactBinaryNatCompletedStatusSameRowsUniformDirect
#print axioms
  compileCompactBinaryNatCompletedStatusSameRowsUniformDirect_payloadLength_le_fixed
