import integration.FoundationCompactNumericListedDirectParserSyntaxRepeatFormulaSyntaxFixedBounds
import integration.FoundationCompactNumericListedDirectParserSyntaxRepeatAtomicFixedBounds
import integration.FoundationCompactNumericListedDirectParserSyntaxRepeatUnconsFullyFixedBounds

open FoundationCompactNumericListedDirectParserSyntaxRepeatFormulaEnvironmentAlignment
open FoundationCompactNumericListedDirectParserSyntaxRepeatFormulaSyntaxFixedBounds
open FoundationCompactNumericListedDirectParserSyntaxRepeatAtomicFixedBounds
open FoundationCompactNumericListedDirectParserSyntaxRepeatUnconsFullCertificate
open FoundationCompactNumericListedDirectParserSyntaxRepeatUnconsFullyFixedBounds

#print axioms
  compactUnifiedParserSyntaxRepeatClosedFormula_environment_alignment
#print axioms
  compactUnifiedParserSyntaxRepeatClosedFormula_code_length_le_fixed
#print axioms
  nativeSuccessorEqCertificate_structuralPayloadBound_le_fixed
#print axioms
  parserSyntaxRepeatUnconsFullFormula_alignment
#print axioms
  parserSyntaxRepeatUnconsGraphCertificate_structuralPayloadBound_le_fullyFixed
