import integration.FoundationCompactNumericListedDirectNatListConsRowsTailEntryCodeBound
import integration.FoundationCompactNumericListedDirectNatListConsRowsTailAtomicRowFixedBounds
import integration.FoundationCompactNumericListedDirectNatListConsRowsTailAtomicRowCodeBound

/-! # Aggregated fixed leaf resources for natural-list cons tail rows -/
