import integration.FoundationCompactNumericListedDirectParserSyntaxAdjacentRowTerminalFullyFixedBounds

open FoundationCompactNumericListedDirectParserStateAtRowsFullyUniformDirectFixedBounds
open FoundationCompactNumericListedDirectParserSyntaxAdjacentStepFullyFixedBounds
open FoundationCompactNumericListedDirectParserSyntaxAdjacentRowTerminalFullyFixedBounds

#print axioms compactParserStateAtRowsIndexFullyUniformDirectFixedBound
#print axioms compactParserStateAtRowsEntryFullyUniformDirectFixedBound
#print axioms compileDirectFourConjunctionSingletonGeneralBound
#print axioms
  compactUnifiedParserStateAtRowsAtValuationIndexFullyUniformDirectFixedBound
#print axioms compileDirectThreeConjunctionSingletonGeneralBound
#print axioms compactParserSyntaxAdjacentStepFullyFixedBoundOfGraph
#print axioms compactParserSyntaxAdjacentRowTerminalFullyFixedBound
