import integration.FoundationCompactNumericListedDirectFormulaTransformTermOutputRowsComparisonGuardFixedBounds

open FoundationCompactNumericListedDirectFormulaTransformTermOutputRowsGuardFixedBounds

#print axioms zeroTagGuardPayloadEnvelope_le_fixed
#print axioms zeroTagGuardCertificate_structuralPayloadBound_le_fixed
#print axioms oneTagGuardPayloadEnvelope_le_fixed
#print axioms oneTagGuardCertificate_structuralPayloadBound_le_fixed
#print axioms capturedGuardPayloadEnvelope_le_fixed
#print axioms capturedGuardCertificate_structuralPayloadBound_le_fixed
#print axioms residualGuardPayloadEnvelope_le_fixed
#print axioms residualGuardCertificate_structuralPayloadBound_le_fixed
