import integration.FoundationCompactPAClosedAtomicCompilerBounds
import integration.FoundationCompactPAValuationTermCompiler

/-!
# Direct compiler for explicit bounded-witness guards

The target is the exact guard generated by `bexsLTSucc`.  The proof stays in
short-binary arithmetic: it proves the corresponding closed strict-order
literal, transports binary one to the PA one term, and never constructs the
unary numeral for `bound`.
-/

open LO FirstOrder LO.FirstOrder LO.FirstOrder.Arithmetic

noncomputable section

set_option maxRecDepth 32768
set_option maxHeartbeats 2000000
set_option Elab.async false

namespace FoundationCompactPABoundedWitnessGuardCompiler

open FoundationSuccinctFiniteConsistencyTarget
open FoundationPudlakQuantitativeConditions
open FoundationCompactBinaryNumeralTerm
open FoundationCompactListedCertifiedVerifier
open FoundationCompactPAQuantitativeCompilerCore
open FoundationCompactPAQuantitativeCompilerCore.CertifiedPAProof
open FoundationCompactPAQuantitativeFunctionCongruence
open FoundationCompactPAQuantitativeOrder
open FoundationCompactPAQuantitativeOrderBounds
open FoundationCompactPABinaryNumeralAddition
open FoundationCompactPABinaryNumeralAdditionBounds
open FoundationCompactPABinaryNumeralMultiplication
open FoundationCompactPABinaryNumeralMultiplicationBounds
open FoundationCompactPAValuationTermCompiler
open FoundationCompactPAClosedAtomicCompiler
open FoundationCompactPAClosedAtomicCompiler.ClosedPATerm
open FoundationCompactPAClosedAtomicCompilerBounds
open FoundationCompactPAClosedAtomicCompilerBounds.ClosedPATerm

def boundedWitnessGuardFormula (value bound : Nat) : ValuationFormula :=
  “!!(shortBinaryNumeralTerm value) <
    !!(shortBinaryNumeralTerm bound) + 1”

private def boundedWitnessGuardBinaryRight (bound : Nat) : ValuationTerm :=
  paAddTerm (shortBinaryNumeralTerm bound) (shortBinaryNumeralTerm 1)

private def boundedWitnessGuardTargetRight (bound : Nat) : ValuationTerm :=
  paAddTerm (shortBinaryNumeralTerm bound) paOneTerm

private def boundedWitnessGuardLeftExpression (value : Nat) : ClosedPATerm :=
  .numeral value

private def boundedWitnessGuardRightExpression (bound : Nat) : ClosedPATerm :=
  .add (.numeral bound) (.numeral 1)

private theorem boundedWitnessGuardFormula_eq_pa
    (value bound : Nat) :
    boundedWitnessGuardFormula value bound =
      (“!!(shortBinaryNumeralTerm value) <
        !!(boundedWitnessGuardTargetRight bound)” : ValuationFormula) := by
  unfold boundedWitnessGuardFormula boundedWitnessGuardTargetRight
  simp [Semiterm.Operator.operator, Semiterm.Operator.Add.term_eq,
    Semiterm.Operator.numeral_one, Matrix.fun_eq_vec_two, Rew.func,
    paAddTerm, paOneTerm, arithmeticOneTerm]
  change Rew.emb (LO.FirstOrder.Semiterm.func Language.One.one ![]) =
    LO.FirstOrder.Semiterm.func Language.One.one ![]
  simp

private noncomputable def boundedWitnessGuardRightEquality (bound : Nat) :
    CertifiedPAProof
      (“!!(boundedWitnessGuardBinaryRight bound) =
        !!(boundedWitnessGuardTargetRight bound)” : ValuationFormula) := by
  let left := shortBinaryNumeralTerm bound
  let binaryOne := shortBinaryNumeralTerm 1
  let reflexive := proveEqualityReflexivityAtTerm left
  let raw := proveAddCongruence left binaryOne left paOneTerm
    reflexive proveShortBinaryOneEqualsPaOne
  exact CertifiedPAProof.cast
    (addEqualityAsTerm_formula left binaryOne left paOneTerm) raw

private theorem boundedWitnessGuardSourceTruth
    (value bound : Nat) (hvalue : value ≤ bound) :
    PositiveLessThanCertificate
      (boundedWitnessGuardLeftExpression value)
      (boundedWitnessGuardRightExpression bound) := by
  simp [PositiveLessThanCertificate, boundedWitnessGuardLeftExpression,
    boundedWitnessGuardRightExpression, ClosedPATerm.value]
  omega

private theorem boundedWitnessGuardSourceFormula_alignment
    (value bound : Nat) :
    (“!!(boundedWitnessGuardLeftExpression value).term <
      !!(boundedWitnessGuardRightExpression bound).term” :
        ValuationFormula) =
      (“!!(shortBinaryNumeralTerm value) <
        !!(boundedWitnessGuardBinaryRight bound)” : ValuationFormula) := by
  rfl

private noncomputable def boundedWitnessGuardSourceProof
    (value bound : Nat) (hvalue : value ≤ bound) :
    CertifiedPAProof
      (“!!(shortBinaryNumeralTerm value) <
        !!(boundedWitnessGuardBinaryRight bound)” : ValuationFormula) := by
  exact CertifiedPAProof.cast
    (boundedWitnessGuardSourceFormula_alignment value bound)
    (provePositiveLessThan
      (boundedWitnessGuardLeftExpression value)
      (boundedWitnessGuardRightExpression bound)
      (boundedWitnessGuardSourceTruth value bound hvalue))

private noncomputable def boundedWitnessGuardTransportedProof
    (value bound : Nat) (hvalue : value ≤ bound) :
    CertifiedPAProof
      (“!!(shortBinaryNumeralTerm value) <
        !!(boundedWitnessGuardTargetRight bound)” : ValuationFormula) :=
  proveLtTransport
    (shortBinaryNumeralTerm value)
    (boundedWitnessGuardBinaryRight bound)
    (shortBinaryNumeralTerm value)
    (boundedWitnessGuardTargetRight bound)
    (proveEqualityReflexivityAtTerm (shortBinaryNumeralTerm value))
    (boundedWitnessGuardRightEquality bound)
    (boundedWitnessGuardSourceProof value bound hvalue)

noncomputable def proveBoundedWitnessGuard
    (value bound : Nat) (hvalue : value ≤ bound) :
    CertifiedPAProof (boundedWitnessGuardFormula value bound) := by
  exact CertifiedPAProof.cast
    (boundedWitnessGuardFormula_eq_pa value bound).symm
    (boundedWitnessGuardTransportedProof value bound hvalue)

/-! ## Public bit-length bound -/

def boundedWitnessGuardBitWidth (value bound : Nat) : Nat :=
  (Nat.size value + 1) + ((Nat.size bound + 1) + (Nat.size 1 + 1))

def boundedWitnessGuardTermCodeEnvelope (bitWidth : Nat) : Nat :=
  compilerTermCodeEnvelope 5 bitWidth

def boundedWitnessGuardSourcePayloadPolynomial (bitWidth : Nat) : Nat :=
  (4 * 1) * compilerLocalCostEnvelope 5 bitWidth +
    (4 * 3) * compilerLocalCostEnvelope 5 bitWidth +
    positiveBinaryNumeralPayloadPolynomial bitWidth +
    orderStepCostEnvelope bitWidth +
    2 * paPrimitiveCostEnvelope
      (boundedWitnessGuardTermCodeEnvelope bitWidth) +
    2 * orderPrimitiveCostEnvelope
      (boundedWitnessGuardTermCodeEnvelope bitWidth)

/-- A fixed polynomial in the sum of the two binary input widths. -/
def boundedWitnessGuardPayloadPolynomial (bitWidth : Nat) : Nat :=
  boundedWitnessGuardSourcePayloadPolynomial bitWidth +
    paMultiplicationLocalCostEnvelope bitWidth +
    4 * paPrimitiveCostEnvelope
      (boundedWitnessGuardTermCodeEnvelope bitWidth) +
    2 * orderPrimitiveCostEnvelope
      (boundedWitnessGuardTermCodeEnvelope bitWidth)

private theorem boundedWitnessGuardSourceProof_payloadLength_le
    (value bound : Nat) (hvalue : value ≤ bound) :
    (boundedWitnessGuardSourceProof value bound hvalue).payloadLength ≤
      boundedWitnessGuardSourcePayloadPolynomial
        (boundedWitnessGuardBitWidth value bound) := by
  have hraw := provePositiveLessThan_payloadLength_le_polynomial
    (boundedWitnessGuardLeftExpression value)
    (boundedWitnessGuardRightExpression bound)
    (boundedWitnessGuardSourceTruth value bound hvalue)
  have hcast :
      (boundedWitnessGuardSourceProof value bound hvalue).payloadLength =
        (provePositiveLessThan
          (boundedWitnessGuardLeftExpression value)
          (boundedWitnessGuardRightExpression bound)
          (boundedWitnessGuardSourceTruth value bound hvalue)).payloadLength := by
    unfold boundedWitnessGuardSourceProof
    exact CertifiedPAProof.cast_payloadLength _ _
  rw [hcast]
  change
    (provePositiveLessThan
      (boundedWitnessGuardLeftExpression value)
      (boundedWitnessGuardRightExpression bound)
      (boundedWitnessGuardSourceTruth value bound hvalue)).payloadLength ≤
        positiveLessThanPayloadPolynomial
          (boundedWitnessGuardLeftExpression value)
          (boundedWitnessGuardRightExpression bound)
  exact hraw

private theorem boundedWitnessGuardRightEquality_payloadLength_le
    (bound bitWidth : Nat) (hbound : Nat.size bound ≤ bitWidth)
    (hpositive : 1 ≤ bitWidth) :
    (boundedWitnessGuardRightEquality bound).payloadLength ≤
      paMultiplicationLocalCostEnvelope bitWidth +
        2 * paPrimitiveCostEnvelope
          (boundedWitnessGuardTermCodeEnvelope bitWidth) := by
  let left := shortBinaryNumeralTerm bound
  let binaryOne := shortBinaryNumeralTerm 1
  let reflexive := proveEqualityReflexivityAtTerm left
  let oneProof := proveShortBinaryOneEqualsPaOne
  let raw := proveAddCongruence left binaryOne left paOneTerm
    reflexive oneProof
  let termBound := boundedWitnessGuardTermCodeEnvelope bitWidth
  have honeSize : Nat.size 1 ≤ bitWidth := by
    simp only [Nat.size_one]
    exact hpositive
  have hleftGenerated : PACompilerGeneratedTerm bitWidth 1 left := by
    exact .numeral bound hbound
  have hbinaryOneGenerated :
      PACompilerGeneratedTerm bitWidth 1 binaryOne := by
    exact .numeral 1 honeSize
  have honeGenerated : PACompilerGeneratedTerm bitWidth 1 paOneTerm :=
    .one
  have hleftCode : (binaryTermCode left).length ≤ termBound := by
    exact generatedAuxTerm_code_length_le_compiler
      (nodeBudget := 5) hleftGenerated (by omega)
  have hbinaryOneCode : (binaryTermCode binaryOne).length ≤ termBound := by
    exact generatedAuxTerm_code_length_le_compiler
      (nodeBudget := 5) hbinaryOneGenerated (by omega)
  have honeCode : (binaryTermCode paOneTerm).length ≤ termBound := by
    exact generatedAuxTerm_code_length_le_compiler
      (nodeBudget := 5) honeGenerated (by omega)
  have hreflexive : reflexive.payloadLength ≤
      paPrimitiveCostEnvelope termBound := by
    exact proveEqualityReflexivityAtTerm_payloadLength_le_primitive
      left termBound hleftCode
  have hone : oneProof.payloadLength ≤
      paMultiplicationLocalCostEnvelope bitWidth := by
    exact proveShortBinaryOneEqualsPaOne_payloadLength_le_local bitWidth
  have hraw : raw.payloadLength ≤
      reflexive.payloadLength + oneProof.payloadLength +
        paPrimitiveCostEnvelope termBound := by
    exact proveAddCongruence_payloadLength_le_primitive
      left binaryOne left paOneTerm reflexive oneProof termBound
      hleftCode hbinaryOneCode hleftCode honeCode
  have hcast :
      (boundedWitnessGuardRightEquality bound).payloadLength =
        raw.payloadLength := by
    unfold boundedWitnessGuardRightEquality
    exact CertifiedPAProof.cast_payloadLength _ _
  rw [hcast]
  change raw.payloadLength ≤
    paMultiplicationLocalCostEnvelope bitWidth +
      2 * paPrimitiveCostEnvelope termBound
  omega

theorem proveBoundedWitnessGuard_payloadLength_le_polynomial
    (value bound : Nat) (hvalue : value ≤ bound) :
    (proveBoundedWitnessGuard value bound hvalue).payloadLength ≤
      boundedWitnessGuardPayloadPolynomial
        (boundedWitnessGuardBitWidth value bound) := by
  let bitWidth := boundedWitnessGuardBitWidth value bound
  let termBound := boundedWitnessGuardTermCodeEnvelope bitWidth
  let left := shortBinaryNumeralTerm value
  let binaryRight := boundedWitnessGuardBinaryRight bound
  let targetRight := boundedWitnessGuardTargetRight bound
  let leftEquality := proveEqualityReflexivityAtTerm left
  let rightEquality := boundedWitnessGuardRightEquality bound
  let source := boundedWitnessGuardSourceProof value bound hvalue
  have hvalueSize : Nat.size value ≤ bitWidth := by
    dsimp only [bitWidth]
    unfold boundedWitnessGuardBitWidth
    omega
  have hboundSize : Nat.size bound ≤ bitWidth := by
    dsimp only [bitWidth]
    unfold boundedWitnessGuardBitWidth
    omega
  have honeSize : Nat.size 1 ≤ bitWidth := by
    simp only [Nat.size_one]
    dsimp only [bitWidth]
    unfold boundedWitnessGuardBitWidth
    omega
  have hleftGenerated : PACompilerGeneratedTerm bitWidth 1 left :=
    .numeral value hvalueSize
  have hboundGenerated : PACompilerGeneratedTerm bitWidth 1
      (shortBinaryNumeralTerm bound) :=
    .numeral bound hboundSize
  have hbinaryOneGenerated : PACompilerGeneratedTerm bitWidth 1
      (shortBinaryNumeralTerm 1) :=
    .numeral 1 honeSize
  have honeGenerated : PACompilerGeneratedTerm bitWidth 1 paOneTerm :=
    .one
  have hbinaryRightGenerated :
      PACompilerGeneratedTerm bitWidth 3 binaryRight := by
    exact .add hboundGenerated hbinaryOneGenerated
  have htargetRightGenerated :
      PACompilerGeneratedTerm bitWidth 3 targetRight := by
    exact .add hboundGenerated honeGenerated
  have hleftCode : (binaryTermCode left).length ≤ termBound := by
    exact generatedAuxTerm_code_length_le_compiler
      (nodeBudget := 5) hleftGenerated (by omega)
  have hbinaryRightCode : (binaryTermCode binaryRight).length ≤ termBound := by
    exact generatedAuxTerm_code_length_le_compiler
      (nodeBudget := 5) hbinaryRightGenerated (by omega)
  have htargetRightCode : (binaryTermCode targetRight).length ≤ termBound := by
    exact generatedAuxTerm_code_length_le_compiler
      (nodeBudget := 5) htargetRightGenerated (by omega)
  have hleftEquality : leftEquality.payloadLength ≤
      paPrimitiveCostEnvelope termBound := by
    exact proveEqualityReflexivityAtTerm_payloadLength_le_primitive
      left termBound hleftCode
  have hrightEquality : rightEquality.payloadLength ≤
      paMultiplicationLocalCostEnvelope bitWidth +
        2 * paPrimitiveCostEnvelope termBound := by
    exact boundedWitnessGuardRightEquality_payloadLength_le
      bound bitWidth hboundSize (by
        dsimp only [bitWidth]
        unfold boundedWitnessGuardBitWidth
        omega)
  have hsource : source.payloadLength ≤
      boundedWitnessGuardSourcePayloadPolynomial bitWidth := by
    dsimp only [source, bitWidth]
    exact boundedWitnessGuardSourceProof_payloadLength_le
      value bound hvalue
  have htransport := proveLtTransport_payloadLength_le_primitive
    left binaryRight left targetRight leftEquality rightEquality source
    termBound hleftCode hbinaryRightCode hleftCode htargetRightCode
  have htransported :
      (boundedWitnessGuardTransportedProof value bound hvalue).payloadLength ≤
        leftEquality.payloadLength + rightEquality.payloadLength +
          source.payloadLength + 2 * orderPrimitiveCostEnvelope termBound := by
    simpa [boundedWitnessGuardTransportedProof, left, binaryRight,
      targetRight, leftEquality, rightEquality, source] using htransport
  have hcast :
      (proveBoundedWitnessGuard value bound hvalue).payloadLength =
        (boundedWitnessGuardTransportedProof
          value bound hvalue).payloadLength := by
    unfold proveBoundedWitnessGuard
    exact CertifiedPAProof.cast_payloadLength _ _
  rw [hcast]
  unfold boundedWitnessGuardPayloadPolynomial
  dsimp only [bitWidth, termBound] at *
  omega

theorem proveBoundedWitnessGuard_verifier_eq_true
    (value bound : Nat) (hvalue : value ≤ bound) :
    listedCompactCertifiedPAProofVerifier
      (proveBoundedWitnessGuard value bound hvalue).code
      (compactFormulaCode (boundedWitnessGuardFormula value bound)) = true :=
  (proveBoundedWitnessGuard value bound hvalue).verifier_eq_true

#print axioms proveBoundedWitnessGuard
#print axioms proveBoundedWitnessGuard_payloadLength_le_polynomial
#print axioms proveBoundedWitnessGuard_verifier_eq_true

end FoundationCompactPABoundedWitnessGuardCompiler
